#!/usr/bin/env python3
"""Convert the exported question-bank workbook into a uni-app data module."""

import argparse
import json
import re
import xml.etree.ElementTree as ET
import zipfile
from pathlib import Path


MAIN_NS = "http://schemas.openxmlformats.org/spreadsheetml/2006/main"
NS = {"x": MAIN_NS}
OPTION_COLUMNS = (("A", "J"), ("B", "K"), ("C", "L"), ("D", "M"), ("E", "N"), ("F", "O"))


def read_rows(workbook_path):
    with zipfile.ZipFile(workbook_path) as archive:
        root = ET.fromstring(archive.read("xl/worksheets/sheet1.xml"))

    rows = []
    for row in root.findall(".//x:sheetData/x:row", NS):
        values = {}
        for cell in row.findall("x:c", NS):
            match = re.match(r"[A-Z]+", cell.attrib.get("r", ""))
            value = cell.find("x:v", NS)
            if match:
                values[match.group(0)] = "" if value is None else (value.text or "")
        rows.append(values)
    return rows


def clean_text(value):
    value = value or ""
    value = re.sub(r"\s*\[图片:\s*https?://[^\]]+\]", "", value)
    value = value.replace("\u3000", " ").replace("\u2003", " ")
    return value.strip()


def build_bank(rows):
    questions = []
    chapter_map = {}

    for row in rows[1:]:
        if row.get("R") != "可查看" or not row.get("H"):
            continue

        options = [
            {"alias": alias, "text": clean_text(row.get(column))}
            for alias, column in OPTION_COLUMNS
            if clean_text(row.get(column))
        ]
        # Image-only options cannot be rendered reliably across H5 and mini-program builds.
        if len(options) < 2:
            continue

        answers = [part.strip() for part in row.get("P", "").split(",") if part.strip()]
        if len(options) == 2 and options[0]["text"] == "对" and options[1]["text"] == "错":
            answers = [{"1": "A", "0": "B"}.get(answer, answer) for answer in answers]

        option_aliases = {option["alias"] for option in options}
        invalid_answers = [answer for answer in answers if answer not in option_aliases]
        if invalid_answers:
            raise ValueError(f"Question {row.get('S') or row.get('A')} has invalid answers: {invalid_answers}")

        chapter_id = str(row.get("C", ""))
        chapter_name = clean_text(row.get("D"))

        question = {
            "id": f"ipf-{row.get('S') or row.get('A')}",
            "subjectId": "junior-personal-finance",
            "chapterId": chapter_id,
            "chapter": chapter_name,
            "section": clean_text(row.get("E")),
            "knowledge": clean_text(row.get("F")),
            "type": "multiple" if len(answers) > 1 else "single",
            "title": clean_text(row.get("H")),
            "options": options,
            "answer": answers,
            "explanation": clean_text(row.get("Q")) or "暂无解析",
        }
        questions.append(question)

        chapter = chapter_map.setdefault(
            chapter_id,
            {"id": chapter_id, "subjectId": "junior-personal-finance", "name": chapter_name, "count": 0},
        )
        chapter["count"] += 1

    chapters = sorted(chapter_map.values(), key=lambda item: int(item["id"]) if item["id"].isdigit() else 999)
    return questions, chapters


def write_module(output_path, questions, chapters):
    output_path.mkdir(parents=True, exist_ok=True)
    header = "// Generated by scripts/import-question-bank.py. Do not edit by hand.\n\n"
    grouped = {}
    for question in questions:
        grouped.setdefault(question["chapterId"], []).append(question)

    for chapter_id, chapter_questions in grouped.items():
        content = header + "export default " + json.dumps(chapter_questions, ensure_ascii=False, indent=2) + "\n"
        (output_path / f"chapter-{chapter_id}.js").write_text(content, encoding="utf-8")

    loaders = "\n".join(
        f"\t'{chapter_id}': () => import('./chapter-{chapter_id}.js').then(module => module.default)"
        + ("," if index < len(grouped) - 1 else "")
        for index, chapter_id in enumerate(grouped)
    )
    catalog_content = (
        header
        + "export const QUESTION_BANK_VERSION = '2026-08-21'\n\n"
        + "export const chapters = "
        + json.dumps(chapters, ensure_ascii=False, indent=2)
        + "\n\nexport const subjectQuestionCounts = { 'junior-personal-finance': "
        + str(len(questions))
        + " }\n"
    )
    (output_path / "catalog.js").write_text(catalog_content, encoding="utf-8")

    index_content = (
        header
        + "import { chapters } from './catalog.js'\n\n"
        + "export { QUESTION_BANK_VERSION, chapters, subjectQuestionCounts } from './catalog.js'\n\n"
        + "const chapterLoaders = {\n"
        + loaders
        + "\n}\n\n"
        + "export function loadQuestionsByChapter(chapterId) {\n"
        + "\tconst loader = chapterLoaders[String(chapterId)]\n"
        + "\treturn loader ? loader() : Promise.resolve([])\n"
        + "}\n\n"
        + "export function loadQuestionsBySubject(subjectId) {\n"
        + "\tif (subjectId !== 'junior-personal-finance') return Promise.resolve([])\n"
        + "\treturn Promise.all(chapters.map(item => loadQuestionsByChapter(item.id)))\n"
        + "\t\t.then(groups => groups.reduce((all, group) => all.concat(group), []))\n"
        + "}\n"
    )
    (output_path / "index.js").write_text(index_content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    questions, chapters = build_bank(read_rows(args.input))
    write_module(args.output, questions, chapters)
    print(f"Imported {len(questions)} questions across {len(chapters)} chapters")


if __name__ == "__main__":
    main()
